- name: configure backend server
  hosts: backend
  become: yes
  vars:


  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y


  - name: enble nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:  # only works for redhat
      name: nodejs
      state: installed

  - name: create expense user
    ansible.builtin.user:
      name: expense  

  - name: Create app directory
    ansible.builtin.file:
      name: /app
      state: directory #when you mention state yes then only directory will create          