- name: configure backend server
  hosts: backend
  become: yes
  vars:


  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y


  - name: enble nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:  # only works for redhat
      name: nodejs
      state: installed

  - name: create expense user
    ansible.builtin.user:
      name: expense  

  - name: Create app directory
    ansible.builtin.file:
      name: /app
      state: directory # when you mention state yes then only directory will create

  - name: download backend code
    ansible.builtin.get_url:   
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip # by default checkes in ansible server
      dest: /app 
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
                     